#ifndef ALERT_ENGINE_H
#define ALERT_ENGINE_H

#include "sensor_processor.h"
#include <string>
#include <vector>

// Represents a single alert generated by threshold checking
struct Alert {
    std::string timestamp;
    std::string parameter;   // e.g., "Temperature", "Soil Moisture", "Humidity", "Water Level"
    std::string condition;   // e.g., "TOO_HIGH", "TOO_LOW"
    float value;
    float threshold;
    std::string message;
};

// Rule-based alert engine matching the Tinkercad firmware conditions:
//   - Soil Moisture: < 400 (LED1 D12)
//   - Humidity: < 400 (LED2 D11)
//   - Temperature: > 30.0°C (LED3 D10) (and < 10.0°C for extreme cold)
//   - Water Level: < 400 (LED4 D9)
class AlertEngine {
public:
    AlertEngine();

    // Check a sensor reading against all thresholds.
    // Returns a list of alerts (empty if all values are within normal range).
    std::vector<Alert> checkThresholds(const SensorReading& reading) const;

    // Get a summary string for an alert suitable for display/logging.
    static std::string formatAlert(const Alert& alert);

private:
    float tempMin_;
    float tempMax_;
    float humidityMin_;
    float soilMin_;
    float waterMin_;
};

#endif // ALERT_ENGINE_H
